name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: godot-tester
      # You may pin to the exact commit or the version.
      # uses: croconut/godot-tester@360be4611a7cc344b6741735880725c7859ad0a6
      uses: croconut/godot-tester@v2.5
      with:
        version: 3.4
        release_type: stable
        # Give relative path to your project.godot, if not in top level of repo
        path: app
