name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: godot-tester
      uses: croconut/godot-tester@v2.5
      with:
        version: 3.4
        release_type: stable
        # Give relative path to your project.godot, if not in top level of repo
        path: app
        # Full path to your GUT config file, e.g. 'res://<path>/<config>.json'.
        config-file: 'res://app/addons/gut/gut_config.gd'
